# -*- coding: utf-8 -*-
{
    'name': 'Gestion des Timesheets PSI',
    'version': '1.0',
    'category': 'Timesheet',
    'sequence': 0,
    'description': """Gestion des Timesheet chez PSI-M""",
    'website': 'https://www.ingenosya.mg',
    'depends': ['hr_timesheet', 'hr_employee_psi'],
    'data':  [
              'data/res_groups.xml',
              'data/ir_model_access.xml',
              'data/hr_timesheet_data.xml',
              'views/resource_views_psi.xml',
              'data/hr_timesheet_cron.xml',
              'data/resource_calendar_data.xml',
              'data/mail_template_hr_timesheet_data.xml',
              'security/ir.model.access.csv',
              'security/hr_holidays_security.xml',
			  'views/hr_timesheet_psi_views.xml',
              'views/hr_timesheet_psi_heures_sup.xml',
             ],
    'demo': [],
    'test': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
