# -*- coding: utf-8 -*-
{
    'name': 'Gestion des absences PSI',
    'version': '1.0',
    'category': 'Human Resources',
    'sequence': 0,
    'description': """Gestion des absences PSI""",
    'website': 'https://www.ingenosya.mg',
    'depends': ['hr_holidays','hr_recruitment_psi','hr_employee_psi','report', 'hr_public_holidays'],
    'data': [
        'security/hr_holidays_security.xml',
        'data/hr_holidays_cron.xml',
        'data/hr_holidays_data.xml',
        'data/mail_template_hr_holidays_data.xml',
        'data/mail_template_validation_wkf.xml',
        'data/holidays_timesheet_data.xml',
        'data/hr_holidays_rule.xml',
        'data/hr_holidays_psi_remove_data.xml',
        'views/hr_holidays_configuration_views.xml',
        'report/report_request_for_absences.xml',
        'report/report_request_for_absences_template.xml',
        'security/ir.model.access.csv',
        'views/hr_holidays_views.xml',
        'views/hr_employee_views.xml',
        ],
    'demo': [],
    'test': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
